name: user_repository

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  inpatient_api:
    path: ../inpatient_api
  domain_models:
    path: ../domain_models
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
