name: inpatient_care_mobile_app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  routemaster: ^1.0.1
  inpatient_api:
    path: packages/inpatient_api
  user_repository:
    path: packages/user_repository
  sign_in:
    path: packages/features/sign_in
  investigation:
    path: packages/features/investigation
  nurse_treatment_sheet:
    path: packages/features/nurse_treatment_sheet
  special:
    path: packages/features/special
  patient_list:
    path: packages/features/patient_list
  summary:
    path: packages/features/summary
  management:
    path: packages/features/management
  domain_models:
    path: packages/domain_models
  component_library:
    path: packages/component_library
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  assets:
    - assets/images/

  uses-material-design: true