name: sign_in
version: 0.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields
  domain_models:
    path: ../../domain_models
  component_library:
    path: ../../component_library

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter: