name: nurse_treatment_sheet
version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  form_fields:
    path: ../../form_fields
  component_library:
    path: ../../component_library

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: